# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
# relative_permalinks: true

repository: dannydenenberg/www

# Setup
title: ×“× ×™××œ's Tech
tagline: "A man, a plan, a canal, panama."
description: "Some of the utterances âœ of dAÃ‘iğ”¼ğŸ…» â……Ã«ğ”‘È¨ğ•Ÿâ„¬ğ”ˆâ“¡â’¢ -- ğŸ­ HUGE theater geek."
url: http://lanyon.getpoole.com
baseurl: ""
paginate: 5

# About/contact
author:
  name: Daniel Denenberg
  url: https://twitter.com/dannydenenberg_
  email: dannydenenberg@gmail.com

github:
  repo: https://github.com/dannydenenberg

# Custom vars
version: 19.7.23 # year.month.day of last edit

plugins: [jekyll-paginate]
