# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty
# relative_permalinks: true

# Setup
title: Danny's Tech ğŸ“½
tagline: ""
description: "Huge theater nerd ğŸ­ğŸ’ƒ."
url: http://hyde.getpoole.com
baseurl: /

author:
  name: "Daniel Denenberg"
  url: https://twitter.com/da_nn_y_o

paginate: 5

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/dannydenenberg/www
  home: https://github.com/dannydenenberg
